language: erlang

env:
  - LUA=""
  - LUA="luajit"

install:
  - sudo apt-get update
  - sudo apt-get install luajit luarocks
  - sudo apt-get install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install lapis
  - sudo luarocks install moonscript
  - sudo luarocks install inspect
  - wget http://openresty.org/download/ngx_openresty-1.7.2.1.tar.gz
  - tar xzvf ngx_openresty-1.7.2.1.tar.gz
  - cd ngx_openresty-1.7.2.1.tar.gz/
  - make try-$LUA
  - make install
  - cd -

script:
  - "lapis server &"
  - "sleep 5"
  - "busted lua/spec"
