language: erlang

env:
  - LUA="luajit"

services:
  - redis-server

install:
  - sudo apt-get update
  - sudo apt-get install luajit luarocks
  - sudo apt-get install libreadline-dev libncurses5-dev libpcre3-dev libssl-dev perl make
  - sudo luarocks install luasec OPENSSL_DIR=/usr OPENSSL_LIBDIR=/usr/lib/x86_64-linux-gnu
  - sudo luarocks install luafilesystem
  - sudo luarocks install busted
  - sudo luarocks install lapis 1.0.4-1
  - sudo luarocks install moonscript
  - sudo luarocks install inspect
  - wget http://openresty.org/download/ngx_openresty-1.7.2.1.tar.gz
  - tar xzvf ngx_openresty-1.7.2.1.tar.gz
  - cd ngx_openresty-1.7.2.1/
  - ./configure --with-luajit
  - make
  - sudo make install
  - cd -
  - cp nginx.conf.example nginx.conf

before_script:
  - "lapis server --trace &"

script:
  - "busted lua/spec"

after_script:
  - "sudo killall nginx"
